alias: Jorrick Automation
description: Automation voorbeeld voor Jorrick
trigger:
  - platform: state
    entity_id:
      - binary_sensor.hue_motion_sensor_toilet_motion
    to: "on"
    id: Beweging Start - Lamp AAN
  - platform: state
    entity_id:
      - binary_sensor.hue_motion_sensor_toilet_motion
    to: "off"
    id: Beweging Stop  - Lamp UIT
    for:
      hours: 0
      minutes: 3
      seconds: 0
condition:
  - condition: or
    conditions:
      - condition: time
        after: "20:00:00"
        before: "08:00:00"
        weekday:
          - fri
          - thu
          - wed
          - tue
          - mon
      - condition: time
        after: "21:00:00"
        before: "09:00:00"
        weekday:
          - sun
          - sat
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Beweging Start - Lamp AAN
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 50
            target:
              entity_id: light.werkkamer_spot_01
      - conditions:
          - condition: trigger
            id:
              - Beweging Stop  - Lamp UIT
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.werkkamer_spot_01
mode: single
