alias: Template - Notificatie v5
description: Template with all notifications combined.
trigger:
  - platform: webhook
    webhook_id: "-7D8SmIGry7U-hjtjg4y4yfgjfgj"
    allowed_methods:
      - POST
      - PUT
    local_only: true
condition: []
action:
  - parallel:
      - service: script.sonos_audio_notificatie_v5
        data:
          media_player_entity: media_player.werkkamer_helmer_sonos
          ruimte: werkkamer_helmer
          notify_phone: iphone_helmer
          notify_tv: lg_tv_woonkamer
          message_tts_body: Dit is een testbericht
          message_tv_body: Dit is een testbericht
          message_phone_body: Testbericht.
          message_phone_title: Test
          message_phone_tag: Test
          message_phone_group: Test
          message_tts_priority: false
      - service: script.sonos_audio_notificatie_v5
        data:
          media_player_entity: media_player.woonkamer_sonos
          ruimte: woonkamer
          notify_phone: iphone_helmer
          notify_tv: lg_tv_woonkamer
          message_tts_body: Dit is een testbericht
          message_tv_body: Dit is een testbericht
          message_phone_body: Testbericht.
          message_phone_title: Test
          message_phone_tag: Test
          message_phone_group: Test
          message_tts_priority: false
mode: single
