alias: BMW - Niet voldoende bereik voor de geplande rit
description: >-
  Check in de agenda en als de afstand van de volgende afspraak (heen en terug)
  > de range van de BMW, dan een notificatie melden.
trigger:
  - platform: time
    at: "19:00:00"
condition: []
action:
  - if:
      - condition: template
        value_template: >-
          {{ ((state_attr("sensor.m365_family_event", "distance") |
          round(0)) * 2) >
          int(states('sensor.i4_edrive40_remaining_range_electric'))}}
    then:
      - service: script.sonos_audio_notificatie_v6
        data:
          media_ruimte: Woonkamer
          message_tts_pre_notify: true
          message_tts_body: >
            Voor de afspraak, {{ states('sensor.waze_event_subject') }}, heeft
            de auto niet voldoende bereik. 
      - service: script.notificatie_iphone_v6
        data:
          action_phone_action_enabled: none
          ruimte: Werkkamer JohnDoe
          notify_phone: iphone_JohnDoe
          persoon: JohnDoe
          notify_location: away
          message_phone_body: >
            Voor de afspraak, {{ states('sensor.waze_event_subject') }}, heeft
            de auto niet voldoende bereik. De range van de BMW is ongeveer {{
            states('sensor.i4_edrive40_remaining_range_electric') }} kilometer,
            maar er is ongeveer {{
            (state_attr("sensor.m365_event_travel_distance", "distance") |
            round(0)) * 2}} kilometer bereik nodig.
          message_phone_title: BMW bereik
          message_phone_tag: bmw_bereik
          message_phone_group: laadpaal
          message_phone_persistent: true
          action_1_phone_single: BMW_I4_LOCK_CAR
          action_1_phone_title: BMW i4 op slot doen
          action_1_phone_activationmode: background
          action_1_phone_icon: sfsymbols:envelope.badge
          action_1_phone_destructive: false
          action_2_phone_single: BMW_I4_FLASH_LIGHT
          action_2_phone_title: Knipper lampen
          action_2_phone_activationmode: background
          action_2_phone_icon: sfsymbols:lightbulb
          action_2_phone_destructive: false
          action_3_phone_single: BMW_I4_HORN_SOUND
          action_3_phone_title: Gebruik claxon
          action_3_phone_activationmode: background
          action_3_phone_icon: sfsymbols:speaker.badge.exclamationmark
          action_3_phone_destructive: false
      - service: script.laadpaal_notificatie_check_laadpaal_beschikbaar
        data: {}
mode: single
