sensor:
  - platform: template
    sensors:
#Waze Information
      waze_event_location:
        friendly_name: "Waze Location"
        value_template: >
          {% set events = state_attr('calendar.familie_m365_JohnDoe',
          'data') %} {% set next_event = events[0] %} {{ next_event.location }}, netherlands
      waze_event_start_time:
        friendly_name: "Waze Event Start Time"
        value_template: >
          {% set events = state_attr('calendar.familie_m365_JohnDoe', 'data') %}
          {% set next_event = events[0] %}
          {{ as_timestamp(next_event.start) | timestamp_custom("%H:%M") }}
      waze_event_subject:
        friendly_name: "Waze Event Subject"
        value_template: >
          {% set events = state_attr('calendar.familie_m365_JohnDoe', 'data') %}
          {% set next_event = events[0] %}
          {{ next_event.summary }}