sensor:
  #Laadpaal 01 - NLALLEGO0134921    
  - platform: rest
    name: NextCharge 01 - NLALLEGO0134921
    scan_interval: 300
    # Go to https://nextcharge.app/ to lookup the charging poles you would like to monitor
    # Go to the Developer mode in your browser (F12 in Edge) and lookup the REST API Url and paste at the resource location in all the REST sensors below (I used a random location in Amsterdam as an example)
    resource: https://nextcharge.webapp.goelectricstations.com/apis/v1_19/getFullStations?lon1=5.001869201660157&lon2=5.104522705078126&lat1=52.31603477280898&lat2=52.36323148534417&plugs=&providers=&hotels=0&restaurants=0&nextcharge=only&status=&access=&evtype=&priceRate=&powerMin=&trafficLayer=false&satellite=false&defaultFilter=false&filterIsReady=true&userId=&favorites=0&userCountry=NL&owner=ITGES&idGroupProvider=
    method: GET
    headers:
      User-Agent: Home Assistant
      Content-Type: application/json
    json_attributes_path: "$.stations[0].connectors[0]"
    json_attributes:
      - idConnector
      - status
      - powerMax
      - physicalReference
    value_template: "{{ value_json.status }}" 

    #Laadpaal 01 - Payment Info - NLALLEGO0134921   
  - platform: rest
    name: NextCharge 01 - Payment - NLALLEGO0134921
    scan_interval: 300
    resource: https://nextcharge.webapp.goelectricstations.com/apis/v1_19/getFullStations?lon1=5.001869201660157&lon2=5.104522705078126&lat1=52.31603477280898&lat2=52.36323148534417&plugs=&providers=&hotels=0&restaurants=0&nextcharge=only&status=&access=&evtype=&priceRate=&powerMin=&trafficLayer=false&satellite=false&defaultFilter=false&filterIsReady=true&userId=&favorites=0&userCountry=NL&owner=ITGES&idGroupProvider=
    method: GET
    headers:
      User-Agent: Home Assistant
      Content-Type: application/json
    json_attributes_path: "$.stations[0].paymentSchemes[1]"
    json_attributes:
      - feeChargeNow-1
      - priceUnit-1
      - feeChargeNow
      - priceUnit
      - connectorId
    value_template: "{{ value_json.status }}"  

  #Laadpaal 02 - NLALLEGO0134922
  - platform: rest
    name: NextCharge 02 - NLALLEGO0134922
    scan_interval: 300
    resource: https://nextcharge.webapp.goelectricstations.com/apis/v1_19/getFullStations?lon1=5.001869201660157&lon2=5.104522705078126&lat1=52.31603477280898&lat2=52.36323148534417&plugs=&providers=&hotels=0&restaurants=0&nextcharge=only&status=&access=&evtype=&priceRate=&powerMin=&trafficLayer=false&satellite=false&defaultFilter=false&filterIsReady=true&userId=&favorites=0&userCountry=NL&owner=ITGES&idGroupProvider=
    method: GET
    headers:
      User-Agent: Home Assistant
      Content-Type: application/json
    json_attributes_path: "$.stations[0].connectors[1]"
    json_attributes:
      - idConnector
      - status
      - powerMax
      - physicalReference
    value_template: "{{ value_json.status }}"    
    
    #Laadpaal 02 - Payment Info - NLALLEGO0134922       
  - platform: rest
    name: NextCharge 02 - Payment - NLALLEGO0134922
    scan_interval: 300
    resource: https://nextcharge.webapp.goelectricstations.com/apis/v1_19/getFullStations?lon1=5.001869201660157&lon2=5.104522705078126&lat1=52.31603477280898&lat2=52.36323148534417&plugs=&providers=&hotels=0&restaurants=0&nextcharge=only&status=&access=&evtype=&priceRate=&powerMin=&trafficLayer=false&satellite=false&defaultFilter=false&filterIsReady=true&userId=&favorites=0&userCountry=NL&owner=ITGES&idGroupProvider=
    method: GET
    headers:
      User-Agent: Home Assistant
      Content-Type: application/json
    json_attributes_path: "$.stations[0].paymentSchemes[0]"
    json_attributes:
      - feeChargeNow-1
      - priceUnit-1
      - feeChargeNow
      - priceUnit
      - connectorId
    value_template: "{{ value_json.status }}"    